name: CI workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install nose coverage
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        flake8 --max-line-length=100
        flake8 --max-line-length=100


    - name: Run unit tests with nose
      run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app


